nestjs/awesome-nestjs

README.md
hey there , please review the examples i added i would love to put them in the awesome list 👯‍♂️
=> Adding more example

README.md
I've created a telegram group for Nestjs
=> Telegram group Nestjs

README.md
Authentication tutorial based on https://docs.nestjs.com/techniques/authentication
=> NestJS Basic Auth and Sessions Tutorial

README.md
I and @bashleigh decided to join forces and we both are maintainers of the repo `nestjs-config`.  This pr amend the URL where you can find the repo! 🎉
=> Updated nestjs-config repo url

README.md
- Adding nestjs-bff project
- Fixed a minor md formatting issue (removed extraneous space)
=> Adding nestjs-bff project

README.md
Hi,
Made a PR to add a new NestJS boilerplate that can be used for new NestJS projects. Crafted for Docker environments and production-ready with TypeORM, logging and Swagger support.
=> Adding "nestjs-template" boilerplate project for Docker environments

README.md
Not sure if I've added this package to the correct section?
=> Added description about AMQP connection manager

README.md
Telegram (Russian speak community)
=> Telegram (Russian speak community)

README.md
Some repos have migrated to new position
=> update some repos url

README.md
NestJS Console is a module that provide a cli. A ready to use service class for your module that exposes the required methods to register commands and sub commands using the npm package commander
=> Adding the nestjs-console module

README.md
This is a really simple package to add pagination types and a method for paginating typeorm objects
=> Added nestjs-typeorm-paginate package

README.md
Starter includes Graphql with Prisma Client, Passport-JWT authentication, Swagger Apo and Docker
=> feat(doc): add awesome nestjs starter with prisma

README.md
nest-i18n offers an easy way to implement i18n support in nestjs application.
=> Added i18n to components

README.md
=> docs: updated URL of nestjs crud

README.md
Nestjsx + nestjs-community is merging into nestjsx-community! Na just nestjsx :p
=> Updated nestjs-community links

README.md
Adding serverless example (which is in production)
=> added serverless example repo

README.md
Shameless plug (I'm the author.) I've got a few people using it now with no complaints so I don't feel bad sharing it with others now 😃.
=> Add the Nestjs Stripe library

README.md
This PR adds Nest Terminus healthcheck module.
=> add Nest Terminus

README.md
=> Add nest js base app template

README.md
This pr adds nestjs-easyconfig module into utilities
=> add nestjs-easyconfig

README.md
Example how to nestjs using the serverless framework with TypeORM
=> Add new Example Serverless-nestjs-Typeorm

README.md
* Fix typo and improve description for Ever Platform
* Add Gauzy Platform
=> Update Ever Platform description and add Gauzy Platform

README.md
Hi,
I am an author of free Udemy Video Tutorial about NestJS. Please, feel free to consider my source and merge PR. There are 8,155 students already enrolled.
More:
[The complete NestJS developer. Enterprise Node.js framework](https://www.udemy.com/course/the-complete-nestjs-developer-enterprise-nodejs-framework/)
=> Free Udemy Video Course

README.md
An example/template for using **`NestJS`** with **`Auth0`**.
=> Add nestjs-auth0

README.md
I wasn't sure where this should be placed, let me know if you want it moved, or a maybe a new graphql section under the `Components & Libraries` section.
=> Add nestjs-query

README.md
Add a great talk from the creator of NestJS.
Here explains how NestJS works in a very clear way.
=> Add Revealing framework fundamentals: NestJS behind the curtain

README.md
Our proposal to kindly add this repository in the examples section.
Before we started this project, we visited the `awesome-nestjs` repo here and were surprised to find no examples using `Firebase`. 
It might be useful for future developers who would like to have similar technology stack as the one implemented in our example repo. :pray: 
https://github.com/mamori-i-japan/mamori-i-japan-api
=> example - FirestoreDB and Firebase Auth

README.md
Adds `nestjs-keycloak-admin` package with supports User Managed Access protocol
=> feat(keycloak): add keycloak admin client with UMA protocol support

README.md
I was not sure wether "Monitoring" was the right category for this, I can move it around if wanted.
=> Add @narando/nest-xray

README.md
Squareboat provides a very awesome nestjs boilerplate, worthy of being listed in here.
=> Added Squareboat's NestJS Boilerplate

README.md
Nonfig combines Configurations and Features. So you change features, and release swiftly, and measure to digital impact.
=> Add Nonfig for Cloud managed configuration management system

README.md
Admin bro provide an automatic interface for CRUD, helps to build fast your application.
=> Added link to admin bro.

README.md
Added Mailman and Eyewitness.
Mailman - https://github.com/squareboat/nest-mailman
Eyewitness - https://github.com/squareboat/nest-eyewitness
=> Added Mailman and Eyewitness

README.md
Stator solves all the commonly found problems of creating a new full-stack project: `configurations`, `coding guidelines`, `releases`, `deployment` and more...
Extract from the project's readme:
Have you ever started a new project by yourself?
If so, you probably know that it is tedious to set up all the necessary tools.
Just like you, the part I enjoy the most is coding, not boilerplate.
stator solves all of this for you by using the **latest technologies' most up-to-date standards**.
Indeed, this template is opinionated as to what's the best, but it does enforce excellent practices such as **code re-usability**, **enforces coding guidelines**, **usage of a monorepo**, etc.
If you want more details about how this idea was implemented, I recommend reading the [series of blog …
=> Added link to stator

README.md
A module to enable multitenancy support with deep integration into the system as whole.
https://github.com/AlexanderC/nestjs-mtenant
=> Adding multitenancy module

README.md
Vendure is a  headless GraphQL ecommerce framework built on Node.js with Nest & TypeScript, with a focus on developer productivity and ease of customization.
https://github.com/vendure-ecommerce/vendure
=> chore: add vendure to projects list

README.md
_Example of constructing a project structure with NestJS_
_https://github.com/CatsMiaow/node-nestjs-structure_
=> Added project structure example

README.md
Automatic SDK generator of NestJS developed backend server for the client developers.
With the **Nestia**, backend developer doesn't need any extra dedication for delivering Rest API to the client developers, like writing `swagger.json` comments. The client developers can call the backend server API just by calling the SDK library functions with await symbol, re-using the interfaces what you've defined.
https://github.com/samchon/nestia
=> Add nestia

README.md
This is a basic NestJS boilerplate project built on the more powerful Node.js framework. The main purpose of this project is to dynamically handle roles and permissions assigned to the user
https://github.com/Ferdysd96/nestjs-permission-boilerplate
=> add: NestJS Permission Boilerplate

README.md
NestJS custom transport strategy for PostgreSQL Pub/Sub.
https://github.com/pvarentsov/nestjs-pg-notify
=> Add NestJS PG Notify

README.md
Clean Architecture based application with NestJS, PostgreSQL and TypeORM.
https://github.com/pvarentsov/typescript-clean-architecture
=> Add TypeScript Clean Architecture example

README.md
Library: A wrapper for the Nest CQRS library for better typing of query and command results
https://github.com/valueadd-poland/nestjs-packages/tree/master/packages/typed-cqrs
=> Add Typed Cqrs

README.md
A production-ready NestJS boilerplate by MonstarLab. Core features: JWT Authentication, RBAC Authorization, TypeORM, winston logger, Pagination, Docker Ready, Auto-generated Swagger. Minor features: prettier, commit-linting husky hooks, SonarCloud github actions, docker-compose.
https://github.com/monstar-lab-oss/nestjs-starter-rest-api
=> feat: NestJS REST starter kit

README.md
Currency conversion module for NestJS
https://github.com/vahidvdn/nestjs-cashify
=> feat: add nestjs-cashify module

README.md
feednext.io domain has been abandoned
=> update feednext link

README.md
🔄 **iola** - a socket client with Rest API.
https://github.com/pvarentsov/iola
=> Add iola socket client

.gitignore, README.md
AsyncAPI documentation generator (based on decorators, like swagger module) for NestJS.
https://github.com/flamewow/nestjs-asyncapi
=> added AsyncAPI module for NestJS

README.md
A redis(ioredis) module for NestJS framework with detailed documentation.
Highlights:
- 100 percent test coverage
Features:
- Support **redis** and **cluster**
- Support health check
- Specify single or multiple clients
- Inject a redis/cluster client via `@InjectRedis()` and `@InjectCluster()` decorator
- Get a redis/cluster client via `RedisService` and `ClusterService`
- Easy to test via `getRedisToken()` and `getClusterToken()`
https://github.com/liaoliaots/nestjs-redis
=> add nestjs-redis package

README.md
Add a github repository showing a way to fully test NestJS with unit, integration and e2e tests.
Use-cases are written in functionnal programming.
Prisma is used for database interactions.
https://github.com/VincentJouanne/nest-clean-architecture-ddd-example
=> chore(docs): add fully tested boilerplate

README.md
NestJS Module for Firebase Admin SDK
NestJS Passport Strategy for Firebase Auth using Firebase Admin SDK
https://github.com/tfarras/nestjs-firebase-admin
https://github.com/tfarras/nestjs-firebase-auth
=> add nestjs firebase auth and firebase admin module

README.md
Remove archived repositories, see issue  #137
=> docs(readme): remove archived repositories

README.md
- [ 1 GitHub Repository:
This library provides deeply integrated protocol-agnostic Nestjs OpenTelemetry instrumentations, metrics and SDK.
https://github.com/MetinSeylan/Nestjs-OpenTelemetry
=> Added OpenTelemetry module

README.md
I updated my Hackathon starter projects' description, which is already listed. Thanks.
=> Update nest-hackathon-starter description

README.md
small improvement for perfection 😻
=> docs(): remove tag br

README.md
Added link anchor for category testing
I forgot to add it in the previous PR, sorry 🙏🏻
=> docs(): added link anchor for category testing

README.md
An API Boilerplate to create a ready-to-use REST API in seconds with NestJS 8.x + TypeORM and Passport Auth JWT 😻
https://github.com/Tony133/nestjs-api-boilerplate-jwt
=> docs(): added link repository nestjs-api-boilerplate-jwt

README.md
Update link for Nest Prisma Startter
https://github.com/notiz-dev/nestjs-prisma-starter
=> Update nest prisma starter url

README.md
=> add pt-br telegram to community category

README.md
Boilerplate with Auth, TypeORM, PostgreSQL, Mailing, I18N, Docker, File uploads (support local and Amazon S3 drivers), Swagger, Tests, CI.
[nestjs-boilerplate](https://github.com/brocoders/nestjs-boilerplate)
=> Added boilerplate for NestJS

README.md
Add an actively developed ESlint rules plugin for NestJS
https://www.npmjs.com/package/@darraghor/eslint-plugin-nestjs-typed
https://github.com/darraghoriordan/eslint-plugin-nestjs-typed
=> docs: Add an actively developed eslint rules plugin

README.md
The nestjs-transport-eventbus module for Nest.
nestjs-transport-eventbus allows broadcasting events via variety of nestjs trasports in easy way
=> The nestjs-transport-eventbus module for Nest.

README.md
Prisma is an ORM that can be used to query a database in NestJS apps. It fully supports TypeScript to avoid runtime errors and improve productivity.
https://docs.nestjs.com/recipes/prisma
https://www.prisma.io/nestjs
=> Add Nest Prisma to Databases

README.md
**ToolJet** is an open-source no-code framework to build and deploy internal tools quickly without much effort from the engineering teams. 
https://github.com/ToolJet/ToolJet
=> Adding  ToolJet to the list: Project using NestJS

README.md
=> drop szokodiakos/typegoose & mentos1386/nest-morgan

README.md
=> add 'NestJS Files' VSCode extension

README.md
nestjs-prisma is a library and schematics adding simple Prisma integration. It provides a `PrismaModule` with configuration options and exposes `PrismaService` which has direct access to the `PrismaClient`.
https://github.com/notiz-dev/nestjs-prisma
=> Add nestjs-prisma library and schematics

README.md
The simplest transactions using Nest and TypeORM
[NPM](https://www.npmjs.com/package/nest-transact), [GitHub](https://github.com/alphamikle/nest_transact)
Articles:
- [Hashnode](https://alphamikle.dev/the-easiest-way-to-make-transactions-in-nestjs)
- [Dev.to](https://dev.to/alphamikle/the-easiest-way-to-use-transactions-in-nest-js-41h0)
- [Hackernoon](https://hackernoon.com/the-most-convenient-ways-of-writing-transactions-within-the-nestjs-typeorm-stack-3q3q33jd)
- [Habr](https://habr.com/ru/post/541866/)
- [Medium](https://itnext.io/how-to-make-transactions-in-nest-js-9bff9b2b02af)
=> add nest-transact package

README.md
A module for creating Discord bots using NestJS, based on Discord.js
NPM: https://www.npmjs.com/package/necord
Repo: https://github.com/SocketSomeone/necord
=> Add necord package

README.md
This was missed in #187
my bad.
=> Fix missing H4 under `Integrations`

README.md
=> Fix missing H4 for `Payment Gateways` under `Integrations`

README.md
Custom Google Cloud Pub/Sub microservice transport for Nest framework.
[_Paste link here._](https://github.com/p-fedyukovich/nestjs-google-pubsub-microservice)
=> docs(): added google pub sub microservice

README.md
Nest.js + Prisma + Yarn Workspaces (Monorepo) full-stack project template
[_Paste link here._](https://github.com/alitnk/nest-prisma-monorepo)
=> Add nest-prisma-monorepo to the list

README.md
let's close https://github.com/nestjs/awesome-nestjs/pull/162
=> chore: remove nestjs london meetup

.gitignore
=> chore(): update .gitignore

README.md
Open source headless CMS API written using NestJS, that has built-in modules like User Management, Role Management, Permission Management, Email Module, Account Settings, 2FA settings, Throttling, RBAC support, Localization, frontend application written with ReactJS & Redux-Saga, UI built with Ant design and many more. Other: a unit test using Jest, prettier, commit-linting husky hooks, PostgreSQL, Redis, docker, etc.
https://github.com/gobeam/truthy
=> chores: update Truthy CMS in boilerplate section

README.md
Amplication is an open‑source development tool. It helps professional Node.js developers develop quality Node.js applications without spending time on repetitive coding tasks.
Amplication auto-generates backend apps built with TypeScript and Node.js, and a client built with React.
It builds database applications with Node.js server built with NestJS and Passport.
https://github.com/amplication/amplication
=> add Amplication

README.md
It's a sample repository that represents how to implement Tactical Domain Driven Design with NestJS.
It is also my answer to this request :D https://discord.com/channels/520622812742811698/808120635682586644/947891663639031858
https://github.com/Sikora00/ddd-by-examples-library-nestjs
=> docs: add ddd example library

README.md
=> Facebook community -  NestJS Poland

README.md
Update nestjs-zeebe link
https://github.com/camunda-community-hub/nestjs-zeebe
=> New home for nestjs-zeebe

README.md
the goal here is to show that the Discord server is pretty popular
=> add badge for discord online members counter

README.md
=> Use package names

README.md
=> docs: add stars badge to nestjs-pact

.github/funding.yml, .github/workflows/funding.yml
=> chore(): update funding.yml

README.md
`samchon/backend` is a template repository for `NestJS`, which utilizes `nestia` and `typeorm`. Its README document is well-formed and helps backend developers how to follow the TDD and BDD principle. In such reason, it's famouse in the South Korea, especially for the newbie backend developers, a little bit.
`nestia-helper` is a transformer library that can boost up `JSON.stringify()` function of API responses about two times faster. I'd hoped to contribute the booster on the `NestJS` core like `nest.Get()` or `nest.Post()`, but @micalevisk advised me to make a new third party library would be better. Therefore, the `nestia-helper` is coming now.
The last, I've updated introduction word …
=> `samchon/backend`, `nestia-helper` and `nestia`

README.md
Added links with their description to the Boilerplate and Utilities section in Components & Libraries.
https://github.com/rudemex/nestjs-starter
https://github.com/tresdoce/tresdoce-nestjs-toolkit
=> docs(readme): add documentation for nestjs starter and toolkit

README.md
A NestJS template, which used the coolest and fastest stuff.
[_Paste link here._](https://github.com/Innei/nest-http-boilerplate)
=> feat: add boilerplate

README.md
Forest Admin provides an off-the-shelf administration panel based on a highly-extensible API plugged into your application.
The agent is compatible with NestJS and can be integrated in an existing NestJS application.
- Repository: https://github.com/ForestAdmin/agent-nodejs
- Documentation: https://docs.forestadmin.com/beta-developer-guide-agents-v2/
- Company: https://www.forestadmin.com
=> Add Forest Admin in the list of integrations

README.md
Nestjs boilerplate with some frequent stuffs added
https://github.com/rubiin/ultimate-nest
=> Feat: add boiler plate ultimate-nest

README.md
Trilon's blog has several posts on NestJS that I believe should be mentioned here as an another good resource. I'm not sure how to mention it tho
https://trilon.io/blog
=> docs: mention trilon.io blog

README.md
=> feat: add Zen to Boilerplate

README.md
=> docs: add NestJS Meetup

README.md
Hot-shots Module for Nest.js Framework. A Node.js client for [Etsy](http://etsy.com/)'s [StatsD](https://github.com/statsd/statsd) server, Datadog's [DogStatsD](https://docs.datadoghq.com/developers/dogstatsd/?tab=hostagent) server, and [InfluxDB's](https://github.com/influxdata/telegraf) Telegraf StatsD server.
https://github.com/SocketSomeone/nestjs-hot-shots
=> feat: add nestjs-hot-shots

README.md
Another Sentry.io module.
[_Paste link here._](https://github.com/ntegral/nestjs-sentry)
=> Add another sentry.io module

README.md
A NestJS library that helps on integrating the Prometheus with NestJS apps.
https://github.com/willsoto/nestjs-prometheus made by @willsoto
=> add nestjs-prometheus lib

README.md
Added a new boilerplate which includes Webpack, Pnpm, Fastify, Swagger, Pino Logger, Airbnb JavaScript Guide, Google JSON Style, ESLint, Prettier, Editorconfig, Husky, Lint-Staged, Commitlint, Axios, Docker, Alias Path, Error Handling and Clustering.
https://github.com/kenso312/nestjs-v9-webpack-boilerplate
=> docs: added a new boilerplate

README.md
https://github.com/omermorad/automock
=> chore: add `@automock/jest` (Automock) under "testing" section

README.md
Repository renamed and updated with various implementation examples to help the NestJS community and all NestJS first-time users 😻 🙌 🚀
=> docs(): update readme.md

README.md
A talk about nestjs CQRS made by Kamil in 2019
https://www.youtube.com/watch?v=c8hvW14VdkY
=> add talk "Taming reactive Node.js: Stream-oriented architecture with NestJS"

README.md
3-day online/onsite training.
https://bottega.com.pl/szkolenie-nestjs
=> docs: trainings

README.md
The code has been moved to a new repository 
_[Paste link here](https://github.com/nestjs-architects/typed-cqrs)._
=> docs: update typed-cqrs repository

README.md
Typegoose integration with NestJS that solves the main problem of nestjs-typegoose, which is completely abandoned.
https://github.com/GrapeoffJS/kindagoose
=> Add Kindagoose

README.md
Lyricstify is a CLI application to show synced Spotify lyrics in the terminal. This app is built with Node, TypeScript, Nest Commander & RxJs.
Since there don't seem to be any sample apps that use the Nest Commander yet, I've created this PR to demonstrate how powerful the Nest Commander can be in real-world applications.
https://github.com/lyricstify/lyricstify
=> Add Lyricstify

README.md
It gained a bit of popularity and seems to be on one of the more extensive pagination helper on NPM now :)
=> Add nestjs-paginate

README.md
NestJS Resilience is an open-source library that provides a set of reliable patterns for building resilient applications on top of NestJS. The library includes several key features, including retry, circuit breaker, and timeout patterns, which help to ensure that your application can handle failures and recover quickly from them.
https://github.com/SocketSomeone/nestjs-resilience
=> chore: add new category and resilience library

README.md
Toolkit is an open-source bot for searching and sending documentation, built with NestJS and Necord.
https://github.com/necordjs/toolkit
=> feat: add necord/toolkit bot

README.md
It's a parsing, validation and serialization library that plays nice with NestJS. The library docs include examples of how to integrate as a NestJS pipe that auto-parses based on the declared type. The value-add is a more flexible parsing and validation approach that uses classes, but allows custom parsing and validation by ad-hoc class methods.  
https://github.com/rsinger86/dto-classes
=> Adds DTO Classes as a new GH repo under "Utilities"

README.md
Undb is a no-code platform designed for open source communities, facilitating easy creation of personalized online databases and project flows without the need for any coding. The platform also offers developer-friendly features such as webhooks and OpenAPI, providing users with flexible and efficient extension interfaces. 
[Github](https://github.com/undb-xyz/undb)
[Demo](https://demo.undb.xyz/me)
[Website](https://www.undb.xyz/)
[Documentation](https://docs.undb.xyz/)
=> Add Undb to projects list

README.md
📜 A lightweight Pagination module for [Necord](https://necord.org/)
https://github.com/necordjs/pagination
=> feat: add necord pagination plugin

README.md
Add template for a best practice for NestJS framework with using Prisma + Postgres, Socket.IO, Zod and Vitest.
https://github.com/Innei/nest-http-prisma-zod
=> feat: add template for NestJS Prisma Vitest and other

README.md
NestJS Authentication without Passport using Bcrypt, JWT and Redis.
https://github.com/anilahir/nestjs-authentication-and-authorization
=> feat: add a NestJS Authentication example without Passport

README.md
Added a new NestJS library
https://github.com/Fcmam5/nest-problem-details
=> feat: add `nest-problem-details` to API libraries

README.md
=> remove `nestjs-stripe` lib

README.md
A tiny utility to support attribute-based exception filtering
https://github.com/micalevisk/nestjs-conditional-exception-filter
=> add `nestjs-conditional-exception-filter` nestjs utility lib

README.md
just notice that I put it nested into _testing_; my bad
=> fix the location of `nestjs-conditional-exception-filter` lib

README.md
=> chore(docs): add chinese docs & speak community

README.md
MurLock: A distributed locking solution for NestJS, providing a decorator for critical sections with Redis-based synchronization. Ideal for microservices and scalable applications.
https://github.com/felanios/murlock
=> add murlock to nestjs utility lib

README.md
I add two nestjs-specific libraries.
1. crud
https://github.com/woowabros/nestjs-library-crud
I've found several open sources that automatically create CRUD APIs, 
but they've either been discontinued or have issues with maintenance.
This is a Typescript library that provides a NestJS decorator which automatically generates CRUD routes of a controller for given TypeORM entity. The decorator generates endpoints for not only create, retrieve one, retrieve many, update, delete but also upsert, recover and search operations for the entity.
2. config
https://github.com/woowabros/nestjs-library-config
I know there is an offical library called configService.
But I wanted to keep the config small …
=> feat: add new library, ( @nestjs-library/config, @nestjs-library/crud )

README.md
=> Remove deleted QQ group

README.md
This module has some costume database validators using class-validator and typeorm
https://github.com/AyubTouba/nestjs-dbvalidator
=> add nestjs-dbvalidator to nestjs utility lib

README.md
=> Add nestjs-spelunker

README.md
the blog post https://hackernoon.com/building-real-time-web-applications-using-nest-js-and-ably-d85887e81f06 is from 2018 and was not updated. Also, the code snippets are not that good to follow along
=> remove outdated tutorial blog post

README.md
A powerful package for gracefully shutting down NestJS applications. 
https://github.com/hienngm/nestjs-graceful-shutdown
=> add `nestjs-graceful-shutdown` package

README.md
=> NestJS and Project Structure

README.md
Teable is a Super fast, Real-time, Professional, Developer friendly, No-code database built on Postgres. It uses a simple, spreadsheet-like interface to create complex enterprise-level database applications. Unlock efficient app development with no-code, free from the hurdles of data security and scalability.
https://github.com/teableio/teable
=> Add Teable

README.md
A package to generate GraphQL types from `zod` contracts. Just pass a `zod` contract to, and it will generate and register suitable GraphQL types for NestJS (usually decorated with `@ObjectType` or `@InputType`).
https://github.com/kolpakov-p/zod-to-nestjs-graphql
=> Add `zod-to-nestjs-graphql` lib

README.md
@necord/localization is a lightweight localization module for [Necord](https://necord.org/). It allows you to easily localize your bot's commands and messages.
https://github.com/necordjs/localization
=> feat: add necord localization plugin

README.md
Integration with Drizzle ORM.
https://github.com/knaadh/nestjs-drizzle
=> Add link to nestjs-drizzle

README.md
=> add NestJS Vienna meetup

README.md
The `NestJS tools` contain libraries written over the past 4 years to provide reusable solutions for applications running in production.
I included three of those libraries, which I think are the most helpful and seemed to be missing during my research for equivalent.
https://github.com/getlarge/nestjs-tools
=> Add NestJS tools libraries related to file storage and AMQP trasnport

README.md
This is a boilerplate for NestJS projects. It is a starting point for building a RESTful API with NestJS.
Some features:
1. Database (TypeORM)
2. Seeding data
3. Config Service
4. Mailing
5. Auth
6. Pagination: Offset and Cursor
7. Internationalization/Translations (I18N)
8. Swagger.
9. E2E and units tests.
10. Docker.
11. CI (Github Actions).
12. Lint & format
13. Documentation (Vuepress)
14. Logging with pino
15. Common exception handling
More new features are on the way...
https://github.com/vndevteam/nestjs-boilerplate
=> feat: add nestjs boilerplate with awesome docs

README.md
=> replace `@fusionworks/ra-data-nest-crud` with an up-to-date fork

README.md
Another type of NestJS websocket supporter, with allows multiple path routes through controller methods.
```typescript
import { TypedRoute, WebSocketRoute } from "@nestia/core";
import { Controller } from "@nestjs/common";
import { Driver, WebSocketAcceptor } from "tgrid";
import { ICalcConfig } from "./api/interfaces/ICalcConfig";
import { ICalcEventListener } from "./api/interfaces/ICalcEventListener";
import { ICompositeCalculator } from "./api/interfaces/ICompositeCalculator";
import { IScientificCalculator } from "./api/interfaces/IScientificCalculator";
import { ISimpleCalculator } from "./api/interfaces/ISimpleCalculator";
import { IStatisticsCalculator } from …
```
=> Add `tgrid` and update `@nestia/core` description.

README.md
Eicrud is a CRUD/Authorization framework extending NestJS. It bring an extra opinionated layer on top of Nest for doing CRUD and role-based access control. List of features includes:
- CRUD services
- Authentication & user management
- Authorization
- Commands
- Validation/Transform
- Database control
- Client
- Monolithic/Microservices
https://github.com/eicrud/eicrud
=> Add Eicrud to the list of open source projects

README.md
This library streamlines the integration of Firebase authentication into your NestJS application. It provides a convenient way to verify Firebase user tokens and includes an optional user role management system, making it easier to control access levels within your app. Additionally, the library exposes the Firebase instance itself, allowing for flexible use of Firebase services such as Firestore, Storage, and more. Whether you're building a small project or scaling up, this tool will help you manage authentication and authorization in a seamless and efficient way.
https://github.com/Alpha018/nestjs-firebase-auth
=> feat: add new references for nestjs-firebase-auth in README

README.md
Apitally is a simple API monitoring & analytics tool with alerting for NestJS (and other Node.js web frameworks). It integrates with NestJS via middleware provided by an open-source client library that is linked here.
https://github.com/apitally/apitally-js
https://docs.apitally.io/frameworks/nestjs
https://apitally.io/nestjs
=> Add Apitally to Monitoring section

README.md
Shopping Mall Backend implementation for the educational purpose.
https://github.com/samchon/shopping-backend
=> Add shopping backend

README.md
Vast Studio a free, purpose-built IDE that makes NestJS development faster and more intuitive by streamlining common tasks like:
- Including common packages (Swagger, validation, configuration, etc.)
- Automatically adding decorators to routes and DTOs
- Providing a fast UI for scaffolding APIs
- Visualizing your app's architecture with a dependency graph
Right now, Vast Studio supports creating Apps, Libraries, Dependencies, Controllers, Routes, and Schemas (DTOs). We're actively working on new features like database entity support, Docker builds, and eventually tools for managing business logic.
[Vast Studio Homepage](https://www.getvast.app/)
- [ x ] **NestJS / Nest**: It's not nest, …
=> Add Vast Studio

README.md
The first `@nestia/chat` is a tool opening Super A.I. chatbot from the OpenAPI document file.
The other `@nestia/editor` is another tool combinig Swagger-UI with online TypeScript IDE of StackBlitz with SDK of RPC functions.
I think `@nestia/chat` can expand the user base of NestJS.
https://github.com/user-attachments/assets/01604b53-aca4-41cb-91aa-3faf63549ea6
- https://nestia.io/docs/swagger/chat/
- https://nestia.io/docs/swagger/editor/
---------------------
This pull request updates the `README.md` file to include new resources related to NestJS. The most important changes are the addition of two new entries under the relevant sections.
New resources added:
* Added `@nestia/editor` …
=> Add `@nestia/chat` and `@nestia/editor`.

README.md
Contextual Logger for NestJS - enables you to enrich your logs with custom context, whenever and wherever you want in NestJS request execution lifecycle.
https://github.com/AdirD/nestjs-context-logger
=> Add nestjs-context-logger to README

README.md
A guide to securing your NestJS API endpoints with Role Based Access Control (RBAC) and Attribute Based Access Control (ABAC).
[https://www.permit.io/blog/how-to-protect-a-url-inside-a-nestjs-app-using-rbac-authorization]
=> Added RBAC/ABAC Guide

README.md
=> add a awesome open-source CRM project used nestjs

README.md
Ghostfolio is a privacy-focused, open-source dashboard that simplifies asset tracking and supports informed financial decisions.
https://github.com/ghostfolio/ghostfolio
=> Add Ghostfolio

README.md
Bunnychess is an open-source scalable chess server based on NestJS gRPC microservices.
It leverages NATS JetStream and its persistent queues to demonstrate how it can be used to build fault-tolerant distributed systems and demonstrates how to integrate it with NestJS.
The microservices are stateless and horizontally scalable, with Redis used to maintain game state.
Additionally, Bunnychess showcases NestJS integration with other key components like Socket.IO and PostgreSQL + Kysely.
https://github.com/pietrobassi/bunnychess
=> feat: add Bunnychess to Projects section

README.md
Idea Forge is a powerful document collaboration platform that combines Notion-like functionality with AI capabilities. It offers a seamless environment for real-time collaborative editing, AI-powered writing assistance, and intuitive document management.
https://github.com/chenxiaoyao6228/idea-forge/
=> Add idea-forge to README
