- README.md
Added two of my nestjs projects.
__nest-raven__ is a sentry raven implementation for nestjs. Is it in correct category or should i put it under Integrations?
__lynx__ is a "framework" built on top of nestjs and typeorm. It's ment to be an example of how nestjs project structure _should_ look like.
> Added nest-raven library and lynx to the list

- README.md
Do not know if LXDHub should be in the **Enterprise Usage** or **Open Source** column, since it is used for Enterprise but is open sourced
> Add lxdhub to open source examples

- README.md
NestJS does now run an official Discord Server.
I also marked the Telegram channel as community maintained, since it was not created by one of the NestJS members as far as I know.
> Add Discord invite to the community resources

- README.md
I've added a "Scheduling" subgroup under the "Integrations" category. It contains a link to the [nest-bull](https://github.com/nestjsx/nest-bull) packages which is a [Bull](https://optimalbits.github.io/bull/) integration for NestJS.
> add nest-bull

- README.md
add - [Nest Mongo Graphql](https://github.com/benawad/nest-mongo-graphql/) - Starter Kit using Nestjs MongoDB Graphql and type-graphql [https://typegraphql.ml/](https://typegraphql.ml/) inspired the type schema first approach
> add example for nest mongo graphql type-graphql

- README.md
A module for creating Telegram bots using NestJS, based on [Telegraf](https://github.com/telegraf/telegraf)
Repo: https://github.com/bukhalo/nestjs-telegraf
> docs: nestjs-telegraf module added

- README.md
Hey! Thx for nice repo. 
Removed lib https://github.com/fresh8/nestjs-grpc-transport (lib is no longer maintaned, and nest now has own official grpc support)
> Remove nestjs-grpc-transport

- README.md
Adds NextJS & NestJS GraphQL Starter
A boilerplate that includes NestJS with NextJS & GraphQL. The boilerplate has GitHub, Reddit & Google OAuth configured and ready to use. The pack also includes Docker configuration for quick and painless deployment.
https://github.com/tomanagle/NextJS-NestJS-GraphQL-Starter
> Added NextJS & NestJS GraphQL Starter

- README.md
OpenTelemetry module for NestJS
https://github.com/pragmaticivan/nestjs-otel
> feat: Add Nest OpenTelemetry (OTEL) to Monitoring

- README.md
A continuation-local storage module compatible with NestJS's dependency injection.
Some common use cases of CLS include:
* Request ID tracing for logging purposes
* Making the Tenant ID available everywhere in multi-tenant apps
* Globally setting the authentication level for the request
Since the package is becoming increasingly popular, I thought I'd add it to the list.
I'm not sure whether I put it in the right category, so please be the judge.
https://github.com/Papooch/nestjs-cls
> docs(): add link to nestjs-cls

- README.md
I wonder if Passport was erroneously included in other project descriptions.
> Remove Passport from Books project description

- README.md
Add a new library called Mockingbird under "Testing" section.
Mockingbird is a nice library to create typed mocks and fixtures easily with decorators
NPM: https://npmjs.com/package/mockingbird
GitHub: https://github.com/omermorad/mockingbird
> docs: add mockingbird library under 'testing' section

- README.md
First-level bullets are replaced by header 4.
<details>
<summary>Moving from this:</summary>
</details>
<details>
<summary>to this:</summary>
</details>
Now we can explore it easier using this GitHub feature:
> Reformatting: use H4 instead of bullet lists to improve discoverability

- README.md
nestjs lib that wraps `axios` package. Can be used as an alternative to `@nestjs/axios` for those that doesn't want to play with rxjs Observables.
https://github.com/benhason1/nestjs-http-promise
> add alternative package to `@nestjs/axios`

- README.md
> Ogma is a no-nonsense logger developed to make logging simple, and easy to read in development, while also having a powerful JSON form when it comes to production level logs, to make it easier to parse and consume by external services. This monorepo has all of the code for the base logger, the binary to rehydrate the JSON logs, and the NestJS Module along with supported plugins for the module's interceptor.
https://github.com/jmcdo29/ogma
> add Ogma logger repo

- README.md
Add PactJS for NestJS package
I'm adding a link to `nestjs-pact` which is a project that connects pact with NestJS with dynamic modules.
https://npmjs.com/package/nestjs-pact
> chore(docs): add pactjs for nestjs

- README.md
I've added the following Shields.io badge
```
```
to display the stars count of github repos at `README.md`
I've skipped fews that I don't think would be that useful to have but I could add them if you don't agree.
> Add stars count badge on every github repo entry

- .github/workflows/links_checker.yml
My first attempt on use https://github.com/lycheeverse/lychee-action to automatically create an issue reporting all bad links. Here's an example of that issue: https://github.com/micalevisk/awesome-nestjs/issues/8 This issue will be created only if there's some bad link on `README.md` file.
Besides that, this workflow will find the last open issue with the label 'report' and update it instead of creating a new one. Or will close it if there's no bad link found.
Not sure if you guys are looking for something like this, tho.
> Add github workflow 'links checker'

- README.md
A command-line tool to generate strongly-typed TypeScript SDKs from NestJS REST API servers.
https://github.com/lonestone/nest-sdk-generator
> add nest-sdk-generator

- README.md
After running the links checer action in my fork, I found that https://typegraphql.ml was broken. It should be https://typegraphql.com
> update link to `type-graphql` docs

- README.md
---
I remove tutorials from 2017 because they were using old APIs. And added a link to the dev.to pages
> drop out-of-date tutorials & minor improvements on that section

- README.md
`ocoda/event-sourcing` is an event-sourcing and CQRS module for NestJS, providing event storage for multiple database providers and the possibility to register custom event-publishers.
For now MongoDB and DynamoDB are supported.
https://github.com/ocoda/event-sourcing
> Add ocoda/event-sourcing

- README.md
typia is a runtime validator library that maximum 15,000x faster than class-validator that NestJS is using.
nestia is a wrapper library of the typia through decorator functions. Also, generating swagger documents or SDK library for client developers like `tRPC` are possible like below:
- https://github.com/samchon/typia
- https://github.com/samchon/nestia
> Add `typia` and refactor `nestia`

- README.md
In nowadays, I've built a new program which can build NestJS project from a `swagger.json` file. Also, ordinary project `@nestia/sdk` started supporting Mockup Simulator generation. Furthermore, `@nestia/sdk` can build e2e test functions automatically by analyzing NestJS server codes.
> If combining both `@nestia/migrate` and `@nestia/sdk`, it is possible to generate SDK and Mockup Simulator only by a `swagger.json` file.
Also, performance of `typia` has been a little bit gained. And I've identified that `@nestia/core` decorators can gain the overall NestJS server performance about 30x times up by benchmark.
- Swagger migration program: https://nestia.io/docs/migrate/
- Mockup Simulator: https://nestia.io/docs/sdk/simulator/
- Automatic e2e test functions generator: …
> Add `@nestia/migrate` and update `nestia` & `typia`

- README.md
A Custom Transporter for NestJS Microservices based on RabbitMQ broker with graceful shutdown.
In the current NestJS RabbitMQ Microservice transport implementation, the framework does execute the message handle but doesn’t take care of it in case of the server shutdown. In case of a shutdown, the handler interrupts its execution without waiting for its finish.
To achieve the graceful shutdown without losing any execution, the custom implementation overrides the handleMessage method by adding a counter of the current executions. This counter allows the Custom Transporter to wait for all handlers before closing Rabbit Channel and Connection. …
> Adding Graceful shutdown example for Microservices

- README.md
This package provides cache decorator factory
It can be used from any storage, so I added Cache section
I posted [article on medium](https://medium.com/p/d71e3140f5e4) too
I will publish this project on npm 25/02/2024(KST)
https://github.com/BJS-kr/nestjs-omacache
> add Cache section & omacahe repo

- README.md
This mono repository contains several packages to simplify the integration of Ory Kratos, Keto, and Hydra 
The following libraries wrap up Ory services API and make them available via dedicated, dynamic modules:
- [keto-client-wrapper](https://github.com/getlarge/nestjs-ory-integration/blob/main/packages/keto-client-wrapper/README.md)
- [kratos-client-wrapper](https://github.com/getlarge/nestjs-ory-integration/blob/main/packages/kratos-client-wrapper/README.md)
- [hydra-client-wrapper](https://github.com/getlarge/nestjs-ory-integration/blob/main/packages/hydra-client-wrapper/README.md)
Each of those libraries has two modules and contains a Guard to make route protection straightforward. …
> add Ory integration libraries

- README.md
Farm is a bundler tool built using rust  https://www.farmfe.org/
Compile with farm as a nest project, compile the project at the millisecond level, greatly optimize the development experience, and then we will use the real runtime form as node's like hmr performance will be greatly improved.
https://github.com/ErKeLost/farm-nestjs-starter
> chore: add `nestjs-farm-starter` example

- README.md
> docs: nestjs boilerplate add to readme

- README.md
A zero-dependency-injection alternative to Prometheus metrics solutions for NestJS.
Effortlessly report metrics from anywhere in your codebase without complex setup or dependency injection
[_Paste link here._](https://github.com/netanelavr/nestjs-metrics-client)
> Add nestjs-metrics-client to the list

- README.md
Following this PR - https://github.com/nestjs/awesome-nestjs/pull/311
updating with the new package name
A zero-dependency-injection alternative to Prometheus metrics solutions for NestJS.
Effortlessly report metrics from anywhere in your codebase without complex setup or dependency injection
[_Paste link here._](https://github.com/netanelavr/nestjs-metrics-client)
> Rename nestjs-metrics-client to nestjs-metrics-reporter

- README.md
two ways on using `@nestjs/swagger` with generic type args
- https://www.inextenso.dev/how-to-generate-generic-dtos-with-nestjs-and-swagger
- https://aalonso.dev/blog/2021/how-to-generate-generics-dtos-with-nestjsswagger-422g
> add articles on how to use generic type args with `@nestjs/swagger`

- README.md
I've used [this script](https://github.com/nestjs/awesome-nestjs/issues/177#issue-1071054818) to spot all the archived GitHub repositories listed in the `README.md` file.
> docs: remove archived github repositories

- README.md
This library automatically generates @nestjs/graphql object types and input types from a Prisma schema. It streamlines the GraphQL code-first workflow by reducing boilerplate and ensuring full type safety.
GitHub: https://github.com/unlight/prisma-nestjs-graphql
npm: https://www.npmjs.com/package/prisma-nestjs-graphql
> docs(nestjs): add prisma-nestjs-graphql to NestJS libraries collection
